<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\picture.png" />
    <None Remove="Images\Products\IMG_KB_164811.png" />
    <None Remove="Images\Products\IMG_KB_164816.png" />
    <None Remove="Images\Products\IMG_KB_185501.png" />
    <None Remove="Images\Products\IMG_KSd_185508.png" />
    <None Remove="Images\Products\IMG_KSd_195207.png" />
    <None Remove="Images\Products\IMG_KSho_185512.png" />
    <None Remove="Images\Products\IMG_KS_195213.png" />
    <None Remove="Images\Products\IMG_KS_195217.png" />
    <None Remove="Images\Products\IMG_KS_195222.png" />
    <None Remove="Images\Products\IMG_MB_174349.png" />
    <None Remove="Images\Products\IMG_MB_191200.png" />
    <None Remove="Images\Products\IMG_MB_191205.png" />
    <None Remove="Images\Products\IMG_MSho_190514.png" />
    <None Remove="Images\Products\IMG_MSho_190518.png" />
    <None Remove="Images\Products\IMG_MSho_191612.png" />
    <None Remove="Images\Products\IMG_MS_185531.png" />
    <None Remove="Images\Products\IMG_MS_185532.png" />
    <None Remove="Images\Products\IMG_MS_185533.png" />
    <None Remove="Images\Products\IMG_WB_170859.png" />
    <None Remove="Images\Products\IMG_WB_170905.png" />
    <None Remove="Images\Products\IMG_WB_170906.png" />
    <None Remove="Images\Products\IMG_WSd_174332.png" />
    <None Remove="Images\Products\IMG_WSd_185156.png" />
    <None Remove="Images\Products\IMG_WSd_185551.png" />
    <None Remove="Images\Products\IMG_WSho_174409.png" />
    <None Remove="Images\Products\IMG_WSho_185202.png" />
    <None Remove="Images\Products\IMG_WSho_185545.png" />
    <None Remove="Images\Products\IMG_WS_174110.png" />
    <None Remove="Images\Products\IMG_WS_185528.png" />
    <None Remove="Images\Products\IMG_WS_185535.png" />
    <None Remove="Images\Products\IMG_WS_185538.png" />
    <None Remove="Images\Чудо Обувь.ico" />
    <None Remove="Images\Чудо Обувь.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="db.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\picture.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KB_164811.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KB_164816.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KB_185501.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KSd_185508.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KSd_195207.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KSho_185512.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KS_195213.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KS_195217.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_KS_195222.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MB_174349.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MB_191200.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MB_191205.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MSho_190514.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MSho_190518.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MSho_191612.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MS_185531.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MS_185532.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_MS_185533.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WB_170859.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WB_170905.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WB_170906.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WSd_174332.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WSd_185156.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WSd_185551.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WSho_174409.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WSho_185202.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WSho_185545.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WS_174110.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WS_185528.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WS_185535.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Products\IMG_WS_185538.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Чудо Обувь.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Чудо Обувь.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
